### PR TITLE
Mandate SSE/SSE2 for x86

### LINKED ISSUE #765: 32bit probably get's wrong floating-point mode.
On x86/x86-64 Julia mandates https://github.com/JuliaLang/julia/blob/a34261f526c0f85a7cacaf2f9e4f17af4af7152d/src/processor_x86.cpp#L992-L994 furthermore we should upgrade generic to at least `pentium4`.

https://github.com/EnzymeAD/Enzyme.jl/blob/3017330cc4316933d0f8f743eac4b4b7acbae8f4/src/compiler/orcv2.jl#L62

### PR DESCRIPTION
**Pull request by vchuravy**
Should fix #765

### CODE REVIEW

File: src/compiler/orcv1.jl [hunk 1]
```diff
@@ -25,7 +25,7 @@ function __init__()
         optlevel = LLVM.API.LLVMCodeGenLevelAggressive
     end
 
-    tm[] = LLVM.JITTargetMachine(optlevel=optlevel)
+    tm[] = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(). cpu_features(); optlevel)
```
Comment (vchuravy) [inline src/compiler/orcv1.jl:28]:
```suggestion
    tm[] = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(), cpu_features(); optlevel)
```

File: src/compiler/orcv2.jl [hunk 2]
```diff
@@ -59,11 +60,11 @@ function __init__()
         optlevel = LLVM.API.LLVMCodeGenLevelAggressive
     end
 
-    tempTM = LLVM.JITTargetMachine(;optlevel=optlevel)
+    tempTM = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(). cpu_features(); optlevel)
```
Comment (vchuravy) [inline src/compiler/orcv2.jl:63]:
```suggestion
    tempTM = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(), cpu_features(); optlevel) 
```

File: src/compiler/orcv2.jl [hunk 3]
```diff
@@ -59,11 +60,11 @@ function __init__()
         optlevel = LLVM.API.LLVMCodeGenLevelAggressive
     end
 
-    tempTM = LLVM.JITTargetMachine(;optlevel=optlevel)
+    tempTM = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(). cpu_features(); optlevel) 
     LLVM.asm_verbosity!(tempTM, true)
     tm[] = tempTM
 
-    tempTM = LLVM.JITTargetMachine(;optlevel)
+    tempTM = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(). cpu_features(); optlevel)
```
Comment (vchuravy) [inline src/compiler/orcv2.jl:67]:
```suggestion
    tempTM = LLVM.JITTargetMachine(LLVM.triple(), cpu_name(), cpu_features(); optlevel)
```
